"""
Common configuration.
"""
API_ENDPOINTS = {
    "station_list": "http://api.irishrail.ie/realtime/realtime.asmx/getAllStationsXML",
    "station_info": "http://api.irishrail.ie/realtime/realtime.asmx/"
    "getStationDataByCodeXML?StationCode=",
}

station_code = {
    "(confey)": "LXCON",
    "(louisa": "LXLSA",
    "adamstown": "ADMTN",
    "and": "SHILL",
    "ardrahan": "ARHAN",
    "arklow": "ARKLW",
    "ashtown": "ASHTN",
    "athenry": "ATHRY",
    "athlone": "ATLNE",
    "athy": "ATHY",
    "attymon": "ATMON",
    "balbriggan": "BBRGN",
    "ballina": "BALNA",
    "ballinasloe": "BSLOE",
    "ballybrophy": "BBRHY",
    "ballycullane": "BCLAN",
    "ballyhaunis": "BYHNS",
    "ballymote": "BMOTE",
    "banteer": "BTEER",
    "bayside": "BYSDE",
    "belfast": "BFSTC",
    "bheag": "MNEBG",
    "birdhill": "BHILL",
    "blackrock": "BROCK",
    "booterstown": "BTSTN",
    "boyle": "BOYLE",
    "bray": "BRAY",
    "bridge)": "LXLSA",
    "bridgetown": "BRGTN",
    "broombridge": "BBRDG",
    "cahir": "CAHIR",
    "campile": "CPILE",
    "canal": "GCDK",
    "carlow": "CRLOW",
    "carrick": "CKOSR",
    "carrick on shannon": "CKOSH",
    "carrick on suir": "CKOSR",
    "carrigaloe": "CGLOE",
    "carrigtwohill": "CGTWL",
    "castlebar": "CLBAR",
    "castleconnell": "CCONL",
    "castleknock": "CNOCK",
    "castlerea": "CSREA",
    "central": "CENTJ",
    "central junction": "CENTJ",
    "charleville": "CVILL",
    "cherry": "PWESF",
    "city": "CITYJ",
    "city junction": "CITYJ",
    "clara": "CLARA",
    "claremorris": "CLMRS",
    "clondalkin": "CLDKN",
    "clongriffin": "GRGRD",
    "clonmel": "CLMEL",
    "clonsilla": "CLSLA",
    "clontarf": "CTARF",
    "clontarf road": "CTARF",
    "cloughjordan": "CJRDN",
    "cobh": "COBH",
    "collooney": "COLNY",
    "connolly": "CNLLY",
    "coolmine": "CMINE",
    "cork": "CORK",
    "craughwell": "CRGHW",
    "curragh": "CURAH",
    "dalkey": "DLKEY",
    "dock": "GCDK",
    "docklands": "DCKLS",
    "donabate": "DBATE",
    "drogheda": "DGHDA",
    "dromod": "DRMOD",
    "drumcondra": "DCDRA",
    "dublin": "PERSE",
    "dublin connolly": "CNLLY",
    "dublin heuston": "HSTON",
    "dublin pearse": "PERSE",
    "dun": "DLERY",
    "dun laoghaire": "DLERY",
    "dunboyne": "DBYNE",
    "dundalk": "DDALK",
    "dunmurray": "DUNMR",
    "edgeworthstown": "ETOWN",
    "enfield": "ENFLD",
    "ennis": "ENNIS",
    "enniscorthy": "ECRTY",
    "europort": "RLEPT",
    "farranfore": "FFORE",
    "fota": "FOTA",
    "foxford": "FXFRD",
    "galway": "GALWY",
    "glenageary": "GLGRY",
    "glounthaune": "GHANE",
    "gorey": "GOREY",
    "gormanston": "GSTON",
    "gort": "GORT",
    "grand": "GCDK",
    "grand canal dock": "GCDK",
    "greystones": "GSTNS",
    "hansfield": "HAFLD",
    "harmonstown": "HTOWN",
    "hazelhatch": "HAZES",
    "heuston": "HSTON",
    "howth": "HOWTH",
    "howth junction": "HWTHJ",
    "junction": "CENTJ",
    "kilbarrack": "KBRCK",
    "kilcock": "KCOCK",
    "kilcoole": "KCOOL",
    "kildare": "KDARE",
    "kilkenny": "KKNNY",
    "killarney": "KLRNY",
    "killester": "KLSTR",
    "killiney": "KILNY",
    "lansdowne": "LDWNE",
    "lansdowne road": "LDWNE",
    "laoghaire": "DLERY",
    "laytown": "LTOWN",
    "leixlip": "LXLSA",
    "leixlip (confey)": "LXCON",
    "leixlip (louisa bridge)": "LXLSA",
    "limerick": "LMRKJ",
    "limerick junction": "LMRKJ",
    "lisburn": "LBURN",
    "littleisland": "LSLND",
    "longford": "LFORD",
    "lurgan": "LURGN",
    "lusk": "RLUSK",
    "m3": "M3WAY",
    "m3 parkway": "M3WAY",
    "malahide": "MHIDE",
    "mallow": "MLLOW",
    "manulla": "MNLAJ",
    "manulla junction": "MNLAJ",
    "maynooth": "MYNTH",
    "midleton": "MDLTN",
    "millstreet": "MLSRT",
    "moira": "MOIRA",
    "monasterevin": "MONVN",
    "monkstown": "SHILL",
    "muine": "MNEBG",
    "muine bheag": "MNEBG",
    "mullingar": "MLGAR",
    "navan": "PHNPK",
    "navan road parkway": "PHNPK",
    "nenagh": "NNAGH",
    "newbridge": "NBRGE",
    "newry": "NEWRY",
    "on": "CKOSR",
    "oranmore": "ORNMR",
    "orchard": "PWESF",
    "parade": "SIDNY",
    "park": "PWESS",
    "park west": "PWESS",
    "park west and cherry orchard": "PWESF",
    "parkway": "PHNPK",
    "pearse": "PERSE",
    "portadown": "PDOWN",
    "portarlington": "PTRTN",
    "portlaoise": "PTLSE",
    "portmarnock": "PMNCK",
    "raheny": "RAHNY",
    "rathdrum": "RDRUM",
    "rathmore": "RMORE",
    "road": "LDWNE",
    "roscommon": "RSCMN",
    "roscrea": "RCREA",
    "rosslare": "RLEPT",
    "rosslare europort": "RLEPT",
    "rosslare strand": "RLSTD",
    "rush": "RLUSK",
    "rush and lusk": "RLUSK",
    "rushbrooke": "RBROK",
    "sallins": "SALNS",
    "salthill": "SHILL",
    "salthill and monkstown": "SHILL",
    "sandycove": "SCOVE",
    "sandymount": "SMONT",
    "seapoint": "SEAPT",
    "shankill": "SKILL",
    "shannon": "CKOSH",
    "sixmilebridge": "SXMBR",
    "skerries": "SKRES",
    "sligo": "SLIGO",
    "strand": "RLSTD",
    "street": "TARA",
    "suir": "CKOSR",
    "sutton": "SUTTN",
    "sydney": "SIDNY",
    "sydney parade": "SIDNY",
    "tara": "TARA",
    "tara street": "TARA",
    "templemore": "TPMOR",
    "thomastown": "THTWN",
    "thurles": "THRLS",
    "tipperary": "TIPRY",
    "tralee": "TRLEE",
    "tullamore": "TMORE",
    "waterford": "WFORD",
    "wellingtonbridge": "WBDGE",
    "west": "PWESS",
    "westport": "WPORT",
    "wexford": "WXFRD",
    "wicklow": "WLOW",
    "woodbrook": "WBROK",
    "woodlawn": "WLAWN",
}
